### ISSUE TITLE
NMS in JAX

### ISSUE THREAD

**Issue by borisdayma** [tirthasheshpatel/segment_anything_keras#2]
Nice repo!

Just in case you were interested, there is a NMS implementation in JAX: see https://github.com/google/flax/discussions/1929#discussioncomment-2378312

**Comment by tirthasheshpatel** [comment]
Thanks @borisdayma for the report :) JAX is now much faster. Slightly faster than both PyTorch and TensorFlow modulo the compilation step!

**Comment by tirthasheshpatel** [comment]
I used Colab's T4 GPU. I will try to run on TPU too once I get some time.
